### ISSUE TITLE
Some icons broken on JetBrains Rider 2022.2.2

### ISSUE THREAD

**Issue by ypedroo** [one-dark/jetbrains-one-dark-theme#264] opened 2022-09-06 18:07 UTC
Describe the bug
I updated the One Dark theme to 5.6.0 and after the update it doesn't work anymore

To Reproduce

Be on JetBrains Rider 2022.2.2
Have One Dark 5.6.0
Use some YAML or Docker running on services
Expected Behavior
Show icons as other theme
![icons-rider-dk](https://user-images.githubusercontent.com/25783175/188707369-fef4c672-2a9f-4cfe-bb72-bf0f6a24584c.png)
s like the images:
![icons rider dk 2](https://user-images.githubusercontent.com/25783175/188707376-e4b2bf3b-b19c-41fa-aef8-faf1be186501.png)

Environment
Licensed to ynoa Pedro
You have a perpetual fallback license for this version.
Subscription is active until August 8, 2023.

Runtime version: 17.0.4+7-b469.44 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET 6.0.6

Screenshots

![icons1](https://user-images.githubusercontent.com/25783175/188707524-38319ff7-cb5c-4228-9a49-ce79148a0a53.png)
![icons2](https://user-images.githubusercontent.com/25783175/188707528-60770f2a-c464-463f-9632-3b9a7aa63c30.png)

**Comment by Unthrottled** [comment] 2022-09-06 22:15
Thanks for taking the time to file this issue.

This is odd because there isn't [any icon customizations](https://github.com/one-dark/jetbrains-one-dark-theme/blob/master/buildSrc/templates/oneDark.template.theme.json#L450). 

I wonder if there is something odd happening with Rider, Custom UI Themes, and how icons are being colored. I might have some time this weekend to try to reproduce. Do the icons still act weird after restarting the IDE?

**Comment by ypedroo** [comment] 2022-09-08 11:46
Yep, sometimes they appear and then go missing afterwards

**Comment by Unthrottled** [comment] 2022-09-11 14:44
Can you give me more steps to reproduce the icons. I am unable to reproduce the icons you've outlined.

<img width="1334" alt="Screen Shot 2022-09-11 at 9 43 06 AM" src="https://user-images.githubusercontent.com/15972415/189533765-526bf656-97c6-43d9-a12b-a13c6e77daae.png">

```
JetBrains Rider 2022.2.2
Build #RD-222.3962.23, built on August 20, 2022
Runtime version: 17.0.4+7-b469.44 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 10
Registry:
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (222.3962.23)
```

You have any plugins installed that recognize specific files?

**Comment by ypedroo** [comment] 2022-09-11 23:11
I was able to identify it in attached folders and for docker desktop on services tab, currently I have none

**Comment by ypedroo** [comment] 2022-09-11 23:11
I'll try and reproduce it on a vm

**Comment by ypedroo** [comment] 2022-09-11 23:11
![image](https://user-images.githubusercontent.com/25783175/189552913-b4c263a4-d5d1-4ded-8099-39765385a21f.png)

**Comment by ypedroo** [comment] 2022-09-21 12:49
an update on this, besides docker desktop the problem lays mainly on heml related items.

**Comment by ypedroo** [comment] 2022-09-21 12:55
Also happens on Linux, i have created up a new env using pop os 22.04 and still happens

**Comment by Unthrottled** [comment] 2022-09-21 13:07
![188707369-fef4c672-2a9f-4cfe-bb72-bf0f6a24584c](https://user-images.githubusercontent.com/15972415/191511374-b004d6ad-e269-4aeb-922b-614c3cb1d879.png)

☝️ what makes these icons, is there a plugin that does that?

Please list any and all installed plugins. Go to `Help` -> `About` then copy, you should get something like this:

```
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 10280M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.click.disable.breakpoints=true
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    io.unthrottled.theme.randomizer (0.5.0)
    com.intellij.properties.bundle.editor (222.4167.21)
    com.fwdekker.randomness (2.7.5)
    io.acari.DDLCTheme (88.1-1.5.0)
    io.unthrottled.amii (1.0.0)
    String Manipulation (9.5.1)
    IdeaVIM (1.11.1)
    GrepConsole (12.15.211.6693.1)
    izhangzhihao.rainbow.brackets (6.26)

Kotlin: 222-1.7.10-release-334-IJ4167.29
```

If I can't reproduce the issue, give me an example project & setup.

**Comment by ypedroo** [comment] 2022-09-23 17:54
```
JetBrains Rider 2022.2.3
Build #RD-222.4167.23, built on September 9, 2022
Licensed to ynoa Pedro
You have a perpetual fallback license for this version.
Subscription is active until August 8, 2023.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-76051900-generic
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 10000M
Cores: 8
Registry:
    ide.windowSystem.autoShowProcessPopup=true
    ide.balloon.shadow.size=0
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    org.toml.lang (222.4167.20)
    org.rust.lang (0.4.178.4873-222)
    org.jetbrains.plugins.go-template (222.4167.21)
    me.seclerp.rider.plugins.efcore (222.1.1)
    eu.gillissen.rider.usersecrets (1.2.0)
    com.vermouthx.idea (1.13.3)
    com.thvardhan.gradianto (4.5)
    com.mintlify.document (1.1.6)
    com.markskelton.one-dark-theme (5.6.0)
    com.jinsihou.react.snippets (1.1.1)
    com.intellij.resharper.StructuredLogging (2022.2.0.241)
    org.intellij.plugins.hcl (222.4167.21)
    com.github.copilot (1.1.31.1908)
    com.intellij.plugin.adernov.powershell (2.0.10)
    Key Promoter X (2022.2)
    zielu.gittoolbox (212.9.9)
    org.sonarlint.idea (7.0.0.52289)
    mobi.hsz.idea.gitignore (4.4.2)
    com.microsoft.vso.idea (1.162.0)
    PythonCore (222.4167.37)
    intellij.prettierJS (222.4167.21)
    com.intellij.resharper.azure (3.50.0.1490-2022.2)
    ir.msdehghan.plugins.ansible (0.92)
    com.github.shiraji.yaemoji (1.0.7)
    com.intellij.kubernetes (222.4167.21)
    ru.adelf.idea.dotenv (2022.2)
    aws.toolkit (1.51-222)
    Abc.MoqComplete.Rider (2022.2.0.2)
    AWSCloudFormation (222.4167.21)

Current Desktop: pop:GNOME
```

**Comment by Unthrottled** [comment] 2022-11-12 01:25
Ah this one took me a bit to understand. I had to create a yaml file with a kubernetes service definition to get the special icon. Please include this type of information in future issues. I don't know how your stuff is set up or what you are using, not a mind reader nor do I know everything 😄 

![image](https://user-images.githubusercontent.com/15972415/201449861-61b27b8c-ade7-4ddf-bf16-017def740325.png)


The icons you are having issues with are from the [k8s plugin you have installed](https://plugins.jetbrains.com/plugin/10485-kubernetes), as to why their icons are having issues rendering with custom ui themes. I didn't try any other custom themes, however I feel like the problem isn't unique to the one dark theme plugin. 

This plugin doesn't do anything special other than using the look and feel API to change colors. It does nothing with icons. So this most likely is an issue with the platform or the kubernetes plugin.

So am going to close this issue.

**Closed as not planned by Unthrottled** 2022-11-12 01:25 UTC
