### ISSUE TITLE
Updated to 5.6.0 and doesn't work anymore in IntelliJ IDEA Ultimate 2022.1.1

### ISSUE THREAD

**Issue by Remzi1993** [one-dark/jetbrains-one-dark-theme#262] opened 2022-06-01 00:04 UTC
**Describe the bug**
I updated the One Dark theme to 5.6.0 and after the update it doesn't work anymore

**To Reproduce**

1. Be on IntelliJ IDEA Ultimate 2022.1.1
2. Update  One Dark theme to 5.6.0
3. After the update it doesn't work anymore, I have tried disabling it and re-enabling it. Also, the theme is not found anymore in the theme list. See screenshot below.

**Expected Behavior**
Update shouldn't break it.

**Environment**
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Licensed to Remzi Cavdar
Subscription is active until September 5, 2022.
For educational use only.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1782M
Cores: 8
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    izhangzhihao.rainbow.brackets (6.23)

Kotlin: 221-1.6.21-release-337-IJ5591.52

**Screenshots**
![idea64_eHfwjrNSZH](https://user-images.githubusercontent.com/980950/171303424-186ec06f-a0eb-4c01-8044-f323260cdd10.png)

**Comment by Remzi1993** [comment] 2022-06-01 00:19
PS: It seems to work if you completely remove the plugin/theme and close the IDE and then start the IDE again and install the plugin fresh again. Seems like there is something going wrong during the upgrade process. Maybe you can look into it.

You could easily test this by installing one version below 5.6.0 on 2022.1.1 and then do an update to 5.6.0 to reproduce the problem and also check what's going on, so that you could maybe solve it. Eventually this issue is going to be frustrating if we need to remove and install the plugin again after every update. There is something going wrong in the upgrade process it seems.

Good luck! I hope I have provided enough information to narrow it down for you to make reproducing and debugging easier.

**Comment by Unthrottled** [comment] 2022-06-02 22:59
I was able to reproduce the issue, thanks for providing the info. 

I'll make sure this is fixed before the next upgrade.

**Comment by Unthrottled** [comment] 2022-06-02 23:22
Huh, when I upgrade from an older version to 5.6.0 then the themes go away. However, after I restart the IDE, I can re-select the themes, does that happen to you?

ENV:

```
JetBrains Rider 2022.1.1
Build #RD-221.5591.20, built on April 28, 2022
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
.NET 6.0.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1504M
Cores: 10
Registry:
    rider.enable.designer.winForms=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    io.unthrottled.theme.randomizer (0.4.0)
    io.acari.normandy.progress.bar (1.9.13)
    com.markskelton.one-dark-theme (5.6.0)
    com.fwdekker.randomness (2.7.5)
    io.acari.DDLCTheme (78.2-1.2.0)
    io.unthrottled.amii (0.14.1)
    io.unthrottled.amii.rider (0.5.1)
    AceJump (3.8.7)
    IdeaVIM (1.10.3)
```

https://user-images.githubusercontent.com/15972415/171753776-4ed2fabf-f27d-46dd-aeb0-f6498034a0f2.mp4

**Comment by Unthrottled** [comment] 2022-06-12 22:55
Tested this out with a new plugin and it also had this issue. Think it is a platform bug, so I submitted an issue https://youtrack.jetbrains.com/issue/IDEA-295921/Dynamic-Theme-Plugins-lost-after-update

**Comment by fgimian** [comment] 2022-06-13 06:16
I experienced the same issue too, just couldn't get the new version working.  v5.5.2 seems to work perfectly though.

Huge thanks for the theme, looks beautiful!
Fotis

**Comment by Remzi1993** [comment] 2022-06-15 14:03
> Huh, when I upgrade from an older version to 5.6.0 then the themes go away. However, after I restart the IDE, I can re-select the themes, does that happen to you?
> 
> ENV:
> 
> ```
> JetBrains Rider 2022.1.1
> Build #RD-221.5591.20, built on April 28, 2022
> Runtime version: 11.0.14.1+1-b2043.45 aarch64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
> macOS 12.4
> .NET 6.0.3
> GC: G1 Young Generation, G1 Old Generation
> Memory: 1504M
> Cores: 10
> Registry:
>     rider.enable.designer.winForms=false
>     ide.new.project.model.index.case.sensitivity=true
>     rdclient.asyncActions=false
>     indexing.enable.entity.provider.based.indexing=false
> 
> Non-Bundled Plugins:
>     io.unthrottled.theme.randomizer (0.4.0)
>     io.acari.normandy.progress.bar (1.9.13)
>     com.markskelton.one-dark-theme (5.6.0)
>     com.fwdekker.randomness (2.7.5)
>     io.acari.DDLCTheme (78.2-1.2.0)
>     io.unthrottled.amii (0.14.1)
>     io.unthrottled.amii.rider (0.5.1)
>     AceJump (3.8.7)
>     IdeaVIM (1.10.3)
> ```
> 
>  one-dark.mp4


I needed to do a clean re-install. Which also helped.

**Comment by Unthrottled** [comment] 2022-09-27 22:34
Doesn't look like there was anything done to https://youtrack.jetbrains.com/issue/IDEA-295921/Dynamic-Theme-Plugins-lost-after-update

But nobody has complained about the latest update, so I'll close this issue, as it isn't an issue with the plugin but the platform. 

Thanks everybody for the supporting information!

**Closed as completed by Unthrottled** 2022-09-27 22:34 UTC
Labels: bug

**Comment by Remzi1993** [comment] 2022-09-27 22:44
@Unthrottled Please 🙏🥺 keep it open so it gets tracked. I don't think it's a good idea to close it. My apologies for the late reply.

I encountered something close to this or maybe connected? 🤔  Clean install Windows 11 and install IntelliJ IDEA and install this theme. It doesn't get automatically activated anymore and you need to manually enable the theme.

**Comment by Unthrottled** [comment] 2022-09-27 22:47
@Remzi1993 I was planning on keeping the YouTrack issue open, so status can be tracked there. 

I currently don't see the value in keeping this (the GitHub issue) open. Because it isn't an issue with the plugin, but the platform. Unless I'm missing something.

**Comment by Remzi1993** [comment] 2022-09-27 22:48
> @Remzi1993 I was planning on keeping the YouTrack issue open, so status can be tracked there.
> 
> I currently don't see the value in keeping this (the GitHub issue) open. Because it isn't an issue with the plugin, but the platform. Unless I'm missing something.

Okay 👍
